customhost = "employee.c9qxr7t032vt.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "12345678"
customdb = "employee"
custombucket = "abdullahsemployeebucket"
customregion = "us-east-1"
